# Recap {#recap}

> "Everyone should have their mind blown once a day."
>
> --- Neil deGrasse Tyson
  
> "Somewhere, something incredible is waiting to be known."
>
> --- Carl Sagan

```{r recap-opts, echo=FALSE}
knitr::opts_chunk$set(
  comment = "R>", 
  warning = FALSE, 
  message = FALSE
)
```

Here recap a bit on what happened...

**Hadley's writing**
Why ensure that your data are tidy? There are two main advantages:

1.  There's a general advantage to picking one consistent way of storing
    data. If you have a consistent data structure, it's easier to learn the
    tools that work with it because they have an underlying uniformity.
2.  There's a specific advantage to placing variables in columns because
    it allows R's vectorised nature to shine. As you learned in
    [mutate](#mutate-funs) and [summary functions](#summary-funs), most 
    built-in R functions work with vectors of values. That makes transforming 
    tidy data feel particularly natural.


## The future

Talk about advanced R options...

-R for biologists
-R for environmental science
-R for oceanographers
-Advanced visualisations
-Multivariate analysis
-Reproducible research
-Basic stats

## Today

A Few sentences about what we intend to do...

Open the floor...